# Generated by Django 3.0.6 on 2021-02-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='c_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
